version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run:
          name: Build
          command: cargo build
      - run:
          name: Run tests
          command: cargo test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build