version: 2
jobs:

  test:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run:
          name: Run tests
          command: cargo test

  build:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run:
          name: Build
          command: cargo build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test